### PR TITLE
[phpstan] init + fixes

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
PHPStan should probably be added to Travis CI build :)

**Comment by TomasVotruba** [comment]
Yea, I forgot that while copying from @Symplify :)
Thanks

**Comment by TomasVotruba** [comment]
Done: https://github.com/Zenify/Zenify/commit/8da0e865937f8504537cea403988c28a039020bc

**Comment by ondrejmirtes** [comment]
👍 :)

**Pull request merged**
