### PR TITLE
Fixed type error in ChangeCodingStandardEventSubscriber + added failing test

### LINKED ISSUE #15: Type error in ChangeCodingStandardEventSubscriber::getMigrationFileByVersion()
Expected string, receives integer

### PR DESCRIPTION
**Pull request by JanMikes**
Fixes #15

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thanks for the PR!

Please fix cs issues: https://travis-ci.org/Zenify/Zenify/jobs/197184287

As for phpstan. Maybe retype here: https://github.com/Lexinek/Zenify/blob/ce571043da8e1647e74958e96376aed675ae442e/packages/DoctrineMigrations/src/EventSubscriber/ChangeCodingStandardEventSubscriber.php#L79

```php
private function getCurrentVersionName() : string
{
	return (string) date('YmdHis');
}
```

Side question: Do you need actually need this subscriber?

**Comment by JanMikes** [comment]
@TomasVotruba well, i was unable to call `php www/index.php migrations:diff` it always ended up with type error and no migration file generated. Or what do you mean, are you thinking about removing it?

Im going to check and fix the issues right now.

**Comment by TomasVotruba** [comment]
> are you thinking about removing it?

Yep. It's actually very magic and very poor replacement for coding standard (which became more popular and strict since then).

Could you please try removing this subscriber service from `/services.neon` and rerun, if it works for you?

**Comment by JanMikes** [comment]
@TomasVotruba sure, haha i love you, after spending 20 minutes of fixing phpstan you suggest to remove the subscriber completely :-) i will go for it and let you know

**Comment by TomasVotruba** [comment]
@Lexinek Well, we talked about it in previous PR, I thought you've read it. Sorry, not my intention to force you to love me :D 

If so, feel free to send removing PR. I'll check them both and resolve it.

**Comment by JanMikes** [comment]
Omg, i did not know that if i push to same branch, the pull request will get updated, so now you have 2 pull requests with same commit 🙈 feel free to pick one and remove the other.

**Comment by TomasVotruba** [comment]
@Lexinek That's fine, similar stuff happens to me all the time :) 

Have you tried it and does it work well?

**Comment by JanMikes** [comment]
Yep, i can now run console commands without type errors 👍

**Pull request closed without merging**
