### PR TITLE
Removed code style modifier

### LINKED ISSUE #15: Type error in ChangeCodingStandardEventSubscriber::getMigrationFileByVersion()
Expected string, receives integer

### PR DESCRIPTION
**Pull request by JanMikes**
Fixes #15
Closes #16

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Very nice, thank you.

All those 280 lines only for this: ` ` I was crazy :D

**Comment by TomasVotruba** [comment]
Any pool results for this @enumag ? 

I'd like to merge it

**Comment by enumag** [comment]
@TomasVotruba No reactions whatsover so I've deleted the topic on nette forum. Merge it.

**Comment by TomasVotruba** [comment]
@enumag Ok. Thank your for it!

**Pull request merged**
